/**
 * App Redux Action Types
 */
export const GET_TABLE_DATA = "GET_TABLE_DATA";
export const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
export const GET_TABLE_DATA_FAILURE = "GET_TABLE_DATA_FAILURE";

export const EDIT_TABLE_DATA = "EDIT_TABLE_DATA";
export const EDIT_TABLE_DATA_SUCCESS = "EDIT_TABLE_DATA_SUCCESS";
export const EDIT_TABLE_DATA_FAILURE = "EDIT_TABLE_DATA_FAILURE";

export const REMOVE_TABLE_DATA = "REMOVE_TABLE_DATA";
export const REMOVE_TABLE_DATA_SUCCESS = "REMOVE_TABLE_DATA_SUCCESS";
export const REMOVE_TABLE_DATA_FAILURE = "REMOVE_TABLE_DATA_FAILURE";